VRA-193 - remove covenant spells
Nitrak/Vocal-Raid-Assistant pull request #204
Opened 2023-02-02 19:00 UTC by nyy23

2023-02-04 21:47 UTC, Nitrak requested changes
Added updated ID's for the covenant spells. The new talents use different IDs.

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[328620] = {type = 1}, --Blessing of Summer
This is not the ID for the talent. This is: 388007

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[304971] = {type = 1}, --Divine Toll
375576

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[327104] = {type = 1}, --Faeline Stomp
388193

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[306830] = {type = 1}, --Elysian Decree
390163

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[325727] = {type = 1}, --Adaptive Swarm
391888

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[325028] = {type = 1}, --Death Chakram
375891

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[307443] = {type = 1}, --Radiant Spark
376103

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[314791] = {type = 1}, --Shifting Power
382440

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[323673] = {type = 1}, --Mindgames
375901

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[323547] = {type = 1}, --Echoing Reprimand
385616

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[323654] = {type = 1}, --Flagellation
384631

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[328305] = {type = 1}, --Sepsis
385408

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[328547] = {type = 1}, --Serrated Bone Spike
385424

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[326059] = {type = 1}, --Primordial Wave
375982

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +		[325640] = {type = 1}, --Soul Rot
386997

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +
remove newline

2023-02-04 21:47 UTC, Nitrak commented on SpellList.lua
> +
remove newline

2023-02-20 18:36 UTC, nyy23 commented
Spell Correction Entries are taken from OmniCD

2023-02-20 19:30 UTC, Nitrak approved these changes

2023-02-20 19:30 UTC, merged