Config Cleanup Error Handling
Nitrak/Vocal-Raid-Assistant pull request #76
Opened 2022-03-08 14:45 UTC by Nitrak

Added error handling for the config cleanup and error message.

2022-03-09 17:58 UTC, nyy23 requested changes

2022-03-09 19:13 UTC, Nitrak commented on VocalRaidAssistant.lua
> +		print(VRA.L["Config Cleaning Error Message"])
Makes sense, I implemented it.

It recalls ConfigCLeanup after ResetDB to set the version number.

2022-03-09 21:58 UTC, nyy23 commented on VocalRaidAssistant.lua
> +		print(VRA.L["Config Cleaning Error Message"])
We should add version to default conf :)

2022-03-10 08:12 UTC, Nitrak commented on VocalRaidAssistant.lua
> +		print(VRA.L["Config Cleaning Error Message"])
Done

2022-03-11 01:44 UTC, nyy23 commented on VocalRaidAssistant.lua
> +		print(VRA.L["Config Cleaning Error Message"])
The error msg will never be visible, since we call this during addon initializing (loadingscreen)

2022-03-11 09:00 UTC, Nitrak commented on VocalRaidAssistant.lua
> +		print(VRA.L["Config Cleaning Error Message"])
I've seen it every time I tested. It will come in the user's chatlog. Maybe there is also a lot of other spam from other addons, :)

2022-03-11 23:55 UTC, merged